name: PyInstaller

on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

  workflow_dispatch:


jobs:
  PyInstallerWindows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.7"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run PyInstaller
        run: |
          pyinstaller "PyInstallerBuild.spec"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: PDF_screenshots.exe
          path: dist/
